
## NUCLEO-F767ZI

MCU ?= cortex-m7
FPU ?= fpv4-sp-d16
ISAFLAGS  = -mcpu=$(MCU) -mfpu=$(FPU) -mfloat-abi=hard -mthumb

VARIANT = NUCLEO_F767ZI

HAL_SRC = STM32F7xx

ARD_CFLAGS :=
ARD_CFLAGS += -DARDUINO=10814
ARD_CFLAGS += -DARDUINO_ARCH_STM32
ARD_CFLAGS += -DARDUINO_LIB_DISCOVERY_PHASE
ARD_CFLAGS += -DARDUINO_NUCLEO_F767ZI
ARD_CFLAGS += -DBOARD_NAME="NUCLEO_F767ZI"
ARD_CFLAGS += -DHAL_UART_MODULE_ENABLED
ARD_CFLAGS += -DSTM32F767xx
ARD_CFLAGS += -DSTM32F7xx

MASS_OPTION = -O "NODE_F767ZI,NUCLEO"

FLASH_SIZE=524288
RAM_SIZE=131072

## Select the serial port for your board
# MONITOR_PORT ?= /dev/ttyACM0
# MONITOR_PORT ?= /dev/ttyUSB0

# ARM_MATH_LIB = $(DISTRO)/ArduinoModule-CMSIS/CMSIS/CMSIS/Lib/GCC -larm_cortexM3l_math
# ARM_MATH_LIB = $(DISTRO)/ArduinoModule-CMSIS/CMSIS/CMSIS/Lib/GCC -larm_cortexM4lf_math

OPENOCD_INTERFACE=stlink
OPENOCD_TARGET=stm32f7x
